language: rust
rust:
  - stable
dist: xenial

sudo: required
matrix:
  include:
    - name: "Dummy"
      script:
        - cargo build

    - name: "Xen"
      install:
        - sudo apt-get install libxen-dev
      script:
        - cargo build --features xen
