[package]
name = "microvmi"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"

[dependencies]
xenctrl = { version = "0.1.0", path = "../xenctrl" }
xenstore = { version = "0.1.0", path = "../xenstore" }
xenforeignmemory = { version = "0.1.0", path = "../xenforeignmemory" }
libc = "0.2.58"

[[bin]]
name = "mem-dump"
path = "src/bin/mem-dump.rs"
