[package]
name = "microvmi"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"

[features]
# Xen driver
xen = ["xenctrl", "xenstore", "xenforeignmemory", "libc"]
# KVM driver
kvm = ["kvmi"]
# Hyper-v driver
hyper-v = []

[dependencies]
log = "0.4.8"
xenctrl = { git = "https://github.com/Wenzel/xenctrl", optional = true }
xenstore = { git = "https://github.com/Wenzel/xenstore", optional = true }
xenforeignmemory = { git = "https://github.com/Wenzel/xenforeignmemory", optional = true }
kvmi = { git = "https://github.com/Wenzel/kvmi.git", optional = true }
libc = { version = "0.2.58", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
