[package]
name = "microvmi"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"

[features]
# Xen driver
xen = ["xenctrl", "xenstore", "xenforeignmemory", "libc"]

[dependencies]
xenctrl = { git = "https://github.com/Wenzel/xenctrl", optional = true }
xenstore = { git = "https://github.com/Wenzel/xenstore", optional = true }
xenforeignmemory = { git = "https://github.com/Wenzel/xenforeignmemory", optional = true }
libc = { version = "0.2.58", optional = true }

[[bin]]
name = "mem-dump"
path = "src/bin/mem-dump.rs"
